Update 0-custom_http_response_header

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,19 +1,35 @@
 #!/usr/bin/env bash
-# Configure Nginx to add a custom HTTP response header
-# Update package lists and install Nginx if not already installed
-apt update
-apt install -y nginx
-# Get the hostname of the current server
-hostname=$(hostname)
-# Create the configuration snippet to add the custom header
-cat << EOF > /etc/nginx/snippets/custom_header.conf
-add_header X-Served-By $hostname;
+# Configure Nginx to add a custom HTTP response header on web-01 and web-02
+
+servers=(
+  "ubuntu@3.84.222.117" # web-01
+  "ubuntu@34.207.253.96" # web-02
+)
+
+for server in "${servers[@]}"; do
+  ssh $server <<EOF
+    # Update package lists and install Nginx if not already installed
+    sudo apt update
+    sudo apt install -y nginx
+
+    # Get the hostname of the current server
+    hostname=\$(hostname)
+
+    # Create or update the configuration snippet to add the custom header
+    sudo tee /etc/nginx/snippets/custom_header.conf > /dev/null << HEADERCONTENT
+    add_header X-Served-By \$hostname;
+HEADERCONTENT
+
+    # Include the custom header snippet in the Nginx configuration if not already included
+    if ! grep -q "include /etc/nginx/snippets/custom_header.conf;" /etc/nginx/sites-enabled/default; then
+      sudo sed -i '/include \/etc\/nginx\/mime.types;/a \    include \/etc\/nginx\/snippets\/custom_header.conf;' /etc/nginx/sites-enabled/default
+    fi
+
+    # Test the Nginx configuration and reload if successful
+    if sudo nginx -t; then
+        sudo systemctl reload nginx
+    else
+        echo "Nginx configuration test failed. Please check the error log for details."
+    fi
 EOF
-# Include the custom header snippet in the Nginx configuration
-sed -i '/include \/etc\/nginx\/mime.types;/a \    include \/etc\/nginx\/snippets\/custom_header.conf;' /etc/nginx/sites-enabled/default
-# Test the Nginx configuration and reload if successful
-if nginx -t; then
-    systemctl reload nginx
-else
-    echo "Nginx configuration test failed. Please check the error log for details."
-fi
+done
